allow use of alternate tags and IPv6-only instances

diff --git a/awsfuncs b/awsfuncs
--- a/awsfuncs
+++ b/awsfuncs
@@ -9,6 +9,12 @@
 # The name of your preferred SSH key for use with AWS.
 AWS_SSH_KEY="${AWS_SSH_KEY:-aws}"
 
+# The name of the preferred tag for our resources.
+# Usually, we use "dualstack", but if you've created
+# IPv6-only resources, you could simply:
+#   export AWS_RESOURCE_TAG="v6only"
+AWS_RESOURCE_TAG="${AWS_RESOURCE_TAG:-dualstack}"
+
 # Default instance type.  Note: some AMIs require
 # specific types, e.g., our NetBSD/amd64 instance
 # won't launch on a t2 instance because it assumes the
@@ -66,18 +72,23 @@ launchInstance() {
 	local ami=${1}
 	local itype=${2:-"${DEFAULT_INSTANCE_TYPE}"}
 	
-	subnet=$(aws ec2 describe-subnets --output json | jq -r '.Subnets[] | select( .Tags[]? | select(.Value == "dualstack")).SubnetId')
+	subnet=$(aws ec2 describe-subnets --output json			\
+			--filter Name=tag-value,Values=${AWS_RESOURCE_TAG} | \
+			jq -r '.Subnets[].SubnetId')
 	if [ -z "${subnet}" ]; then
-		echo "Unable to find subnet labeled 'dualstack'." >&2
+		echo "Unable to find subnet labeled '${AWS_RESOURCE_TAG}'." >&2
 		return 0
 	fi
-	sg=$(aws ec2 describe-security-groups --output json | jq -r '.SecurityGroups [] | select( .GroupName == "dualstack").GroupId')
+	sg=$(aws ec2 describe-security-groups --output json 		\
+			--filter Name=group-name,Values=${AWS_RESOURCE_TAG} | \
+			jq -r '.SecurityGroups[].GroupId')
 	if [ -z "${sg}" ]; then
-		echo "Unable to find security group labeled 'dualstack'." >&2
+		echo "Unable to find security group labeled '${AWS_RESOURCE_TAG}'." >&2
 		return 0
 	fi
 	instance ${ami}				\
 		--instance-type ${itype}	\
+		--metadata-options "HttpProtocolIpv6=enabled"	\
 		--subnet-id "${subnet}"		\
 		--security-group-ids "${sg}" |	\
 		jq -r '.Instances[].InstanceId'
@@ -101,12 +112,19 @@ instanceId() {
 		echo "Usage: instanceId <hostname>" >&2
 		return 0
 	fi
-	if ! expr "${hname}" : "ec2-" >/dev/null 2>&1 ; then
+
+	if ! isEc2Hostname "${hname}"; then
 		echo "'${hname}' does not look like an EC2 name to me." >&2
 		return 0
 	fi
 	_aedi --filters Name=dns-name,Values="${hname}" | \
 		jq -r ".Reservations[].Instances[].InstanceId"
+}
+
+isEc2Hostname() {
+	local hname="${1}"
+
+	echo "${hname}" | egrep -q "^(ec2-.*amazonaws.com)|(.*.ip.aws)$"
 }
 
 # After we start an instance, we have to wait for it
@@ -177,7 +195,7 @@ ec2wait() {
 		echo
 	fi
 
-	if ! ping -q -c 1 "${hostname}" >/dev/null 2>&1 ; then
+	if ! pingHost "${hostname}"; then
 		echo "${hostname} still not up, sorry." 2>&1
 		return 1
 	elif ! sshCheck "${hostname}"; then
@@ -243,7 +261,7 @@ sshCheck() {
 		return 1
 	fi
 
-	if ping -q -c 1 "${hname}" >/dev/null 2>&1 ; then
+	if pingHost "${hname}"; then
 		timeout 2 /bin/sh -c "echo | nc ${hname} 22 >/dev/null 2>&1" >/dev/null 2>&1
 		if [ $? -eq 0 ]; then
 			return 0
@@ -265,10 +283,10 @@ _instanceOperation() {
 		echo "Supported arguments: <hostname|id>" >&2
 		return 0
 	fi
-	if expr "${hname}" : "ec2-" >/dev/null 2>&1 ; then
+	if isEc2Hostname "${hname}"; then
 		hname="$(instanceId ${hname})"
 	elif ! expr "${hname}" : "i-" >/dev/null 2>&1 ; then
-		echo "<hostname|id> should match 'ec2-*' or 'i-*'" >&2
+		echo "<hostname|id> should match 'ec2-*', '.*-ip.aws', or 'i-*'" >&2
 		return 0
 	fi
 
@@ -291,14 +309,14 @@ _id_and_name() {
 	local hname=""
 	local id=""
 
-	if expr "${input}" : "ec2-" >/dev/null 2>&1 ; then
+	if isEc2Hostname "${input}"; then
 		hname="${input}"
 		id="$(instanceId ${input})"
 	elif expr "${input}" : "i-" >/dev/null 2>&1 ; then
 		hname="$(iname ${input})"
 		id="${input}"
 	else
-		echo "<hostname|id> should match 'ec2-*' or 'i-*'" >&2
+		echo "<hostname|id> should match 'ec2-*', '.*.ip.aws', or 'i-*'" >&2
 		return
 	fi
 
@@ -352,6 +370,19 @@ startInstance() {
 
 stopInstance() {
 	_instanceOperation stop-instances "${1}"
+}
+
+pingHost() {
+	local hname="${1}"
+	local ping="ping"
+
+	# IPv6-only resources have public hostnames
+	# like "28zmx-sz37e-0fkdf-a2aib-ynpd9.us-east-1.ip.aws"
+	if expr "${hname}" : ".*ip.aws$" >/dev/null 2>&1 ; then
+		ping="ping6"
+	fi
+
+	${ping} -q -c 1 "${hname}" >/dev/null 2>&1
 }
 
 protectІnstance() {
@@ -432,7 +463,7 @@ attachVolume() {
 	aws ec2 attach-volume --output json --volume-id "${1}" --instance-id "${instance}" --device "${device}"
 }
 
-# Same for detaching, but we don't need to know the
+# Same for detachingk, but we don't need to know the
 # instance-id:
 detachVolume() {
 	local force=""
